CREATE DATABASE IF NOT EXISTS `meibun-db`;
USE `meibun-db`;

CREATE TABLE IF NOT EXISTS users(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
	`name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`password_hash` VARCHAR(255) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS books(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    `sentence` VARCHAR(255) NULL,
	`title` VARCHAR(255) NULL,
	`author` VARCHAR(255) NULL,
	`pages` INT,
	`user_id` INT
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS book_harts(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
	`book_id` INT,
	`hart` INT
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_books(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`user_id` INT NOT NULL,
	`book_id` INT NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_sessions(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL,
    `user_id` INT NOT NULL,
	`token` VARCHAR(255) NULL,
    `expires_at` TIMESTAMP NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users_book_harts(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`book_id` INT NOT NULL,
	`book_hart_id` INT NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
